# Usei o Gemini para organizar os tipos de chamado em categorias mais gerais
CATEGORIAS_TIPO_CHAMADOS = {
    "Infraestrutura e Obras": [
        "Drenagem e Saneamento", # [cite: 1]
        "Vias públicas", # [cite: 1]
        "Pavimentação", # [cite: 1]
        "Fiscalização de obras", # [cite: 1]
        "Engenharia de tráfego", # [cite: 1]
        "Solicitação de obras", # [cite: 1, 2]
        "Instalação e manutenção de contêineres, caçambas e papeleiras", # [cite: 2]
        "Manutenção de iluminação pública", # [cite: 8]
        "Tapa-buraco", # [cite: 8]
        "Conservação de vias", # [cite: 8]
        "Licença de obras", # [cite: 11, 12]
        "Cópia de Projetos", # [cite: 12]
        "Obras em prédios públicos - RioUrbe", # [cite: 14]
        "Calçadas", # [cite: 14]
        "Recapeamento asfáltico", # [cite: 14]
        "Obras irregulares", # [cite: 15]
        "Obras particulares - Licenciamento e Legalização", # [cite: 16]
        "Urbanização de Praças", # [cite: 17]
        "Estrutura Pública", # [cite: 18]
        "Rio Cidade - obras", # [cite: 19]
        "Fechamento de Logradouro Público", # [cite: 19]
        "Sistema de drenagem", # [cite: 20]
        "Arquitetura e Engenharia", # [cite: 22]
        "Projetos Urbanos - SMPU", # [cite: 23]
        "Porto Maravilha", # [cite: 23]
        "GEORIO", # [cite: 24]
        "Obras de controle de enchentes", # [cite: 25]
        "Obras-SMH", # [cite: 26]
        "Obras de concessionárias", # [cite: 27]
        "Implantação de iluminação pública", # [cite: 31]
        "Licenciamento de drenagem e fiscalização", # [cite: 31]
        "Saneamento básico", # [cite: 28]
        "Reformulação de iluminação pública", # [cite: 25, 26]
        "Iluminação Pública" # [cite: 8]
    ],
    
    "Saúde e Vigilância Sanitária": [
        "Arboviroses", # [cite: 1]
        "Controle de vetores", # [cite: 1]
        "Visa Saúde", # [cite: 3]
        "Estabelecimentos e Serviços de Saúde", # [cite: 3]
        "Programas de Saúde", # [cite: 3]
        "Super Centro Carioca de Saúde (SCS)", # [cite: 5]
        "Coordenações de Emergência Regional (CER)", # [cite: 5]
        "Hospitais (HM)", # [cite: 5]
        "Rio Saúde - CERs", # [cite: 5]
        "Rio Saúde - Hospitais", # [cite: 5]
        "Imunizações", # [cite: 5]
        "Engenharia Sanitária", # [cite: 5]
        "Diversos - VISA", # [cite: 5]
        "Informação IVISA", # [cite: 5]
        "CES - Coordenação de Engenharia Sanitária e Outros Estabelecimentos", # [cite: 5, 6]
        "Informação solicitada - VISA", # [cite: 6]
        "SISVISA", # [cite: 6]
        "Rio Saúde - UPAs", # [cite: 8]
        "Unidades de Pronto Atendimento (UPAs)", # [cite: 10]
        "Sistema Nacional de Regulação (SISREG)", # [cite: 10]
        "Saúde", # [cite: 10]
        "Clínicas da Família (CF)", # [cite: 11]
        "Medicamentos", # [cite: 11]
        "Postos de Saúde (PS)", # [cite: 11]
        "Centros de Atenção Psicossocial (CAPS)", # [cite: 11]
        "Vigilância Epidemiológica", # [cite: 11]
        "Violência obstétrica", # [cite: 12]
        "Vigilância sanitária", # [cite: 12]
        "Clínicas da Família", # [cite: 13]
        "Saúde da Família", # [cite: 13]
        "CVA - Coordenação de Alimentos", # [cite: 13]
        "Clínicas conveniadas", # [cite: 14]
        "Postos de saúde", # [cite: 14, 15]
        "Centros de Testagem COVID", # [cite: 15]
        "CVS - Coordenação de Estabelecimentos e Serviços de Saúde", # [cite: 17]
        "Ouvidoria RioSaúde", # [cite: 18]
        "Plano Saúde - ASSIM", # [cite: 18, 19]
        "CVZ - Coordenação de Controle de Zoonoses e Fiscalização de Estabelecimentos Veterinários", # [cite: 21]
        "Cartão SUS", # [cite: 22]
        "Plano Saúde - NotreDame Intermédica", # [cite: 22, 23]
        "CNES", # [cite: 23]
        "LASP - Laboratório de Análise de Saúde Pública", # [cite: 23]
        "Produtos e Serviços para a Saúde", # [cite: 23]
        "CFS - Coordenação de Fiscalização Sanitária", # [cite: 24]
        "Atendimento - coronavírus", # [cite: 25]
        "Rio Saúde - CER Barra", # [cite: 26]
        "RioSaúde - Sede", # [cite: 26]
        "UPAs", # [cite: 30]
        "Rio Saúde - Sede", # [cite: 8]
        "Visa Processos / Licenciamentos", # [cite: 5]
        "Visa Alimentos", # [cite: 5]
        "CCZ" # [cite: 5]
    ],
    
    "Educação e Ensino": [
        "Educação Especial", # [cite: 1]
        "Alimentos e estabelecimentos de ensino", # [cite: 3]
        "Educação Ambiental", # [cite: 9]
        "Programas de educação/projetos", # [cite: 9]
        "Recursos humanos - SME", # [cite: 9]
        "Conflitos educacionais", # [cite: 9]
        "Informação solicitada - SME", # [cite: 9]
        "Gestão escolar", # [cite: 9]
        "Diversos - SME", # [cite: 9]
        "Professores e aspectos pedagógicos", # [cite: 9]
        "Rede particular de ensino infantil", # [cite: 9]
        "Matrícula escolar", # [cite: 9]
        "Transporte para alunos", # [cite: 9]
        "Educação", # [cite: 11, 12]
        "Cursos e capacitações", # [cite: 12]
        "Infraestrutura escolar", # [cite: 14]
        "Violência nas escolas/creches", # [cite: 14]
        "Alimentação escolar", # [cite: 14]
        "Rede particular de ensino", # [cite: 14]
        "Profissionais de apoio da educação", # [cite: 15]
        "Educação Infantil", # [cite: 16]
        "Produtos educacionais", # [cite: 17]
        "Uniforme e material escolar", # [cite: 21]
        "Transporte escolar e fretamento", # [cite: 22]
        "Fora do âmbito municipal - SME", # [cite: 27]
        "Portal da Prefeitura-SME", # [cite: 29]
        "Creche", # [cite: 31]
        "Cursos" # [cite: 6]
    ],
    
    "Transporte, Trânsito e Mobilidade": [
        "Gratuidade de transporte", # [cite: 1]
        "Abrigos", # [cite: 1]
        "Transporte Especial Complementar - TEC", # [cite: 1]
        "BRT (corredor expresso de ônibus)", # [cite: 2]
        "Sinalização Gráfica", # [cite: 3]
        "Regulamentações Viárias", # [cite: 3]
        "Fiscalização Eletrônica", # [cite: 3]
        "Veículo", # [cite: 4]
        "Estacionamento", # [cite: 4]
        "Fiscalizacao de trânsito", # [cite: 4]
        "Estacionamento irregular", # [cite: 4]
        "Semáforo", # [cite: 4]
        "Quebra-molas (OT)", # [cite: 6]
        "Operação de trânsito", # [cite: 6]
        "Guarda Municipal / Fiscalização de trânsito", # [cite: 6]
        "Táxi", # [cite: 8]
        "Veículos", # [cite: 8]
        "Ouvidoria SMTR", # [cite: 11]
        "Multas", # [cite: 11]
        "Ônibus", # [cite: 11]
        "Transportes", # [cite: 12]
        "Bilhetagem eletrônica", # [cite: 12]
        "Táxi e mototáxi", # [cite: 12]
        "Táxi.Rio", # [cite: 12]
        "Ciclovias", # [cite: 13]
        "Sinalização Semafórica", # [cite: 13]
        "Informação solicitada - SMTR", # [cite: 16]
        "Câmeras e Painéis", # [cite: 17]
        "Táxis", # [cite: 17]
        "Ônibus - gratuidade", # [cite: 17]
        "Transporte Complementar", # [cite: 18]
        "Cet-Rio - Engenharia de tráfego", # [cite: 18, 19]
        "Informação solicitada - CETRIO", # [cite: 20]
        "Ônibus - pontos terminais/paradas/itinerários", # [cite: 20, 21]
        "Vans", # [cite: 23]
        "Ônibus - frota", # [cite: 23]
        "Diversos - SMTR", # [cite: 25]
        "Trânsito", # [cite: 25]
        "Recursos de multas de trânsito", # [cite: 27]
        "Processos administrativos - SMTR", # [cite: 29]
        "Mototáxi", # [cite: 29]
        "Assédio no transporte", # [cite: 30]
        "Fora do âmbito municipal - SMTR", # [cite: 31]
        "Ônibus - tarifa" # [cite: 32]
    ],
    
    "Limpeza Urbana e Resíduos": [
        "Coleta domiciliar", # [cite: 2]
        "Limpeza de logradouros", # [cite: 2]
        "Limpeza de margens de rios", # [cite: 2]
        "Fiscalização de caçamba de empresa particular", # [cite: 2]
        "Controle de roedores e caramujos", # [cite: 2]
        "Remoção Gratuita", # [cite: 2]
        "Limpeza e manutenção de praças e parques", # [cite: 2, 3]
        "Fiscalização de Grande Gerador", # [cite: 3]
        "Coleta Seletiva", # [cite: 3]
        "Diversos - Comlurb", # [cite: 6]
        "Resíduos Sólidos", # [cite: 9]
        "Limpeza de praias", # [cite: 12]
        "Informações 1746 - Comlurb", # [cite: 13]
        "Processos administrativos - Comlurb", # [cite: 15]
        "Limpeza", # [cite: 16]
        "Remoção de caçamba de empresa particular", # [cite: 21]
        "Portal da Prefeitura-COMLURB", # [cite: 31]
        "Fora do âmbito municipal - Comlurb" # [cite: 27]
    ],
    
    "Meio Ambiente e Bem-Estar Animal": [
        "Arborização", # [cite: 1]
        "Manejo Arbóreo", # [cite: 2]
        "Proteção de animais", # [cite: 3]
        "Parques urbanos, jardins e praças da Fundação Parques e Jardins", # [cite: 4]
        "Poluição", # [cite: 4]
        "Medicina Veterinária", # [cite: 5]
        "IJV", # [cite: 6]
        "Parques e jardins", # [cite: 6]
        "Danos ao meio ambiente", # [cite: 8]
        "Defesa dos animais", # [cite: 10]
        "Estabelecimentos Veterinários ou de interesse a saúde animal", # [cite: 12, 13]
        "Árvores - Plantio", # [cite: 13]
        "MEIO AMBIENTE", # [cite: 16]
        "CIA - Coordenação de Indústria Agropecuária", # [cite: 17]
        "Diversos - SMAC", # [cite: 18]
        "APA - área de proteção ambiental", # [cite: 18]
        "Informação solicitada - SMAC", # [cite: 18]
        "Licenciamento Ambiental", # [cite: 18]
        "Assistência veterinária", # [cite: 19]
        "Maus tratos com animais", # [cite: 19]
        "Cuidado com os animais", # [cite: 19]
        "Vetores ", # [cite: 22]
        "Jardins - FPJ", # [cite: 22]
        "Diversos - FPJ", # [cite: 25]
        "Manutenção de rios e canais", # [cite: 25]
        "NAGRO", # [cite: 27]
        "Parque Nacional da Tijuca", # [cite: 28]
        "Poluição Hídrica", # [cite: 29]
        "RioZoo", # [cite: 30]
        "Parques", # [cite: 30]
        "Poluição do ar", # [cite: 31]
        "Poluição do Solo/Extrativa", # [cite: 32]
        "Informação solicitada - FPJ" # [cite: 21]
    ],
    
    "Assistência Social, Cidadania e Direitos Humanos": [
        "Atendimento Social", # [cite: 1]
        "Cadastro Único", # [cite: 1]
        "Cartão Família Carioca", # [cite: 1]
        "Direitos da população LGBTQIA+", # [cite: 1]
        "Conselho Tutelar", # [cite: 3]
        "Programas Sociais", # [cite: 9]
        "Ouvidoria SMAS", # [cite: 9]
        "Administrativo - SMAS", # [cite: 9]
        "Racismo,Injúria Racial e Antissemitismo", # [cite: 11]
        "Atendimento à Pessoa com Deficiência", # [cite: 12]
        "Atendimento à mulher em situação de violência", # [cite: 12]
        "Intolerância Religiosa", # [cite: 12]
        "Acessibilidade Digital ", # [cite: 16]
        "Alimentação Popular", # [cite: 16]
        "Auxílio à população", # [cite: 16]
        "Diversos - SMPDA", # [cite: 17]
        "Auxílio ambulante", # [cite: 18]
        "Informação solicitada - SMAS", # [cite: 19]
        "Pedidos de acolhimento", # [cite: 19]
        "Informação solicitada - SMPDA", # [cite: 19]
        "Inclusão Social", # [cite: 20]
        "Atendimento para pessoas com deficiência", # [cite: 20]
        "Maus tratos a idosos", # [cite: 20]
        "Racismo e Intolerância Religiosa", # [cite: 20]
        "Recursos Humanos-SMAS", # [cite: 22]
        "Diversos - SMAS", # [cite: 22]
        "Centros Municipais de Referência da Pessoa com Deficiência", # [cite: 22]
        "Benefícios para terceira idade", # [cite: 24]
        "Auxílio", # [cite: 27]
        "Asilos", # [cite: 27]
        "Assistência Social/Programas sociais", # [cite: 28]
        "Integração Social", # [cite: 29]
        "Ouvidoria SMAS-DH", # [cite: 30]
        "Pessoas Desaparecidas", # [cite: 30]
        "Legislação para pessoas com deficiência", # [cite: 30]
        "Mapa da mulher carioca" # [cite: 26]
    ],
    
    "Ordem Pública e Fiscalização": [
        "Comércio ambulante", # [cite: 1]
        "Outros estabelecimentos comerciais", # [cite: 1]
        "Feiras", # [cite: 1]
        "Mercados, Supermercados e Agroindústrias", # [cite: 2]
        "Ocupação de área pública", # [cite: 2]
        "Publicidade", # [cite: 2]
        "Alimentos e estabelecimentos de ensino", # [cite: 3]
        "Patrulhamento público", # [cite: 4]
        "Perturbação do sossego", # [cite: 4]
        "Ocupação irregular nas calçadas", # [cite: 6]
        "Diversos - GM", # [cite: 6]
        "Defesa do Consumidor", # [cite: 7]
        "Licenciamento, registro e fiscalização de instalações mecânicas", # [cite: 11]
        "Denúncia", # [cite: 12]
        "Ordem pública", # [cite: 14]
        "Poluição sonora", # [cite: 14]
        "Processos administrativos - GM-Rio", # [cite: 15]
        "Fora do âmbito municipal - SEOP", # [cite: 16]
        "Criticas - GM", # [cite: 17, 18]
        "Vistoria anual", # [cite: 19]
        "Estabelecimento irregular", # [cite: 21]
        "Ar Condicionado central, Exaustão Mecânica", # [cite: 21]
        "Furto de Equipamentos", # [cite: 21, 22]
        "Diversos - SEOP", # [cite: 22]
        "Conduta de guarda municipal", # [cite: 22]
        "Administração da GM-Rio", # [cite: 24]
        "Informação solicitada - PROCON CARIOCA", # [cite: 26]
        "Ouvidoria SEOP", # [cite: 27]
        "Portal da Prefeitura-GM-RIO", # [cite: 29]
        "Ocupação Irregular", # [cite: 30]
        "Fora do âmbito municipal - GM-Rio", # [cite: 32]
        "Ouvidoria PROCON CARIOCA" # [cite: 13]
    ],
    
    "Gestão, Finanças e Administração Pública": [
        "Cartões", # Not explicitly distinct, derived from contexts like Cartão Família
        "Certidões", # [cite: 1]
        "Alvará", # [cite: 2]
        "Endereços", # [cite: 2]
        "Atendimento ao cidadão", # [cite: 3]
        "Qualidade do atendimento da Central 1746", # [cite: 3]
        "Pagamentos", # [cite: 4]
        "Servidor público", # [cite: 4]
        "Benefícios / Auxílios", # [cite: 4]
        "Pensão", # [cite: 4]
        "Financiamento Imobiliário", # [cite: 4]
        "IPTU", # [cite: 4]
        "ISS", # [cite: 5]
        "Lei de Acesso à Informação", # [cite: 5]
        "Nota Carioca", # [cite: 5]
        "Processos administrativos - SMS", # [cite: 5]
        "Subprefeitura", # [cite: 6]
        "Prefeito", # [cite: 6]
        "Ouvidoria - IplanRio", # [cite: 7]
        "Dívida Ativa", # [cite: 7]
        "Contrib. Previdenciária", # [cite: 7, 8]
        "Inativos", # [cite: 8]
        "Pensionistas", # [cite: 8]
        "Atendimento - PreviRio", # [cite: 8]
        "Valorização do servidor", # [cite: 8]
        "Concursos públicos", # [cite: 8]
        "IPTU - outros", # [cite: 10]
        "ISS - outros", # [cite: 10]
        "ITBI - outros", # [cite: 10]
        "Informação solicitada - SMF", # [cite: 10]
        "Ouvidoria - SMF", # [cite: 10]
        "Ouvidoria SMH", # [cite: 10]
        "Programas Habitacionais - SMH", # [cite: 10]
        "Acumuladores", # [cite: 11]
        "Trabalho e emprego", # [cite: 11]
        "Imóveis do Patrimônio Municipal", # [cite: 11]
        "Perícia Médica", # [cite: 11]
        "Informações sobre a Prefeitura", # [cite: 11]
        "ITBI", # [cite: 12]
        "Processos", # [cite: 12]
        "Impostos e Taxas", # [cite: 12]
        "Planejamento Urbano - SMPU", # [cite: 12]
        "Diversos - SMS", # [cite: 13]
        "Central 1746", # [cite: 13]
        "Ouvidoria Geral", # [cite: 13]
        "Sistemas - IPLANRIO", # [cite: 13]
        "Informação solicitada - PREVI-RIO", # [cite: 13]
        "Ouvidoria Previ-Rio", # [cite: 13]
        "Desenvolvimento Econômico", # [cite: 14]
        "Patrimônio Imobiliário", # [cite: 14]
        "Questões administrativas - SMS", # [cite: 14]
        "Recursos Humanos - SMS", # [cite: 14]
        "Recursos Humanos SUBSC", # [cite: 15]
        "Diversos - SMDEIS", # [cite: 15]
        "Informação solicitada - SMTR", # [cite: 16]
        "Obras particulares - Licenciamento e Legalização", # [cite: 16]
        "Tramitação Processual", # [cite: 17]
        "IPLANRIO", # [cite: 18]
        "Serviços on line - Previ-Rio", # [cite: 18]
        "Previ-Rio", # [cite: 18]
        "Lei de Proteção de Dados", # [cite: 18]
        "Imóveis Protegidos", # [cite: 18]
        "Concurso Público", # [cite: 19]
        "Legislação tributária", # [cite: 19]
        "Ações Especiais - SMH", # [cite: 19]
        "Gestão Administrativa", # [cite: 20]
        "Lei Geral de Proteção de Dados", # [cite: 20]
        "Contracheque", # [cite: 20]
        "Legislação Municipal", # [cite: 20]
        "Projetos Urbanos - SMDEIS", # [cite: 20]
        "Aplicativos", # [cite: 21]
        "Exames de seleção", # [cite: 21]
        "Clube do Servidor", # [cite: 21]
        "Ressarcimento de Taxas", # [cite: 22]
        "Portal da Prefeitura-SEGOVI", # [cite: 22]
        "Pesquisa Científica", # [cite: 22]
        "CASS", # [cite: 23]
        "Assuntos sobre pagamentos - SUBSC", # [cite: 23]
        "Departamento Pessoal - SUBSC", # [cite: 23]
        "Assuntos da CGP", # [cite: 24]
        "Cadastro técnico - SMDEIS", # [cite: 24]
        "Conselho de Contribuintes do Município", # [cite: 25]
        "Assuntos internos - SUBSC", # [cite: 25]
        "Administração Regional (GELs)", # [cite: 25]
        "Portal da Prefeitura-SMF", # [cite: 25]
        "Logradouros e Numeração", # [cite: 25]
        "Legislação - SMPU", # [cite: 26]
        "Portal da Prefeitura - SUBSC", # [cite: 26]
        "Capacitação", # [cite: 26]
        "Ouvidoria - 1746", # [cite: 26]
        "Herança Jacente", # [cite: 26]
        "Editais", # [cite: 26]
        "Pedido de emprego", # [cite: 27]
        "Regularização Urbanística e Fundiária", # [cite: 27]
        "Transparência e Acesso à Informação", # [cite: 27]
        "Processos administrativos - Rioluz", # [cite: 28]
        "Portal da Prefeitura-SMDEIS", # [cite: 28]
        "Auditorias / Contas públicas", # [cite: 28]
        "Previdência Complementar", # [cite: 28]
        "Portal da Prefeitura-PREVI-RIO", # [cite: 28]
        "Contas públicas", # [cite: 28]
        "CAD - Coordenação de Administração", # [cite: 28]
        "Processos administrativos - SMIT", # [cite: 28]
        "Integridade", # [cite: 29]
        "Órgãos sem ouvidoria", # [cite: 29]
        "Assuntos da Riourbe", # [cite: 29, 30]
        "SEGOVI", # [cite: 30]
        "Superintendência/Administração Regional", # [cite: 30]
        "PAGAMENTO", # [cite: 30]
        "Informações gerais", # [cite: 30]
        "Recursos Humanos", # [cite: 30]
        "Processos administrativos - Seconserva", # [cite: 31]
        "Cursos - Servidor Municipal", # [cite: 31]
        "Informação solicitada - Superintendências", # [cite: 31]
        "Ativo- PGM" # [cite: 31]
    ],
    
    "Cultura, Turismo, Esporte e Lazer": [
        "Esporte e lazer", # [cite: 9]
        "MultiRio", # [cite: 5]
        "Programação Cultural", # [cite: 11]
        "Atividades Esportivas", # [cite: 12]
        "Turismo", # [cite: 16]
        "Pontos Turísticos", # [cite: 16]
        "Equipamentos culturais", # [cite: 17]
        "Naves do Conhecimento", # [cite: 17]
        "Eventos (CEPEV)", # [cite: 17]
        "Carnaval", # [cite: 18]
        "Informações sobre programas/capacitações", # [cite: 18]
        "Atividades culturais", # [cite: 19]
        "Vilas Olímpicas", # [cite: 23]
        "Bibliotecas", # [cite: 23]
        "Rock in Rio", # [cite: 23]
        "Teatros", # [cite: 24]
        "Equipamentos de praças", # [cite: 25]
        "Incentivo Cultural", # [cite: 26]
        "Centros Esportivos", # [cite: 26]
        "Parques Esportivos e de Lazer", # [cite: 26]
        "Outros Eventos - Riotur", # [cite: 27]
        "Bibliotecas/Arquivo da cidade", # [cite: 27]
        "SMTUR", # [cite: 28]
        "Informação Turística", # [cite: 28]
        "Ouvidoria RIOTUR", # [cite: 28]
        "Réveillon", # [cite: 28]
        "Patrimônio cultural", # [cite: 29]
        "Cidade das Artes", # [cite: 29]
        "RioFilme", # [cite: 30]
        "Bilheteria-Cidade das Artes", # [cite: 30]
        "Outros equipamentos - SMC", # [cite: 30]
        "Cultura", # [cite: 31]
        "Lonas Culturais", # [cite: 31]
        "Divulgação da cidade", # [cite: 32]
        "Diversos - RIOTUR", # [cite: 20]
        "Projetos de Esportes e Lazer" # [cite: 15]
    ],
    
    "Defesa Civil e Geotecnia": [
        "Estrutura de Imóvel", # [cite: 4]
        "Geotecnia", # [cite: 4]
        "Defesa civil", # [cite: 4]
        "Documento - Defesa Civil", # [cite: 4]
        "Monumentos e Chafarizes", # [cite: 4]
        "Informação solicitada - Defesa Civil", # [cite: 15]
        "Interdição de imóvel", # [cite: 17]
        "Encostas", # [cite: 17]
        "Vistorias - Defesa Civil", # [cite: 25]
        "Diversos - Defesa Civil", # [cite: 26]
        "Ouvidoria Defesa Civil", # [cite: 30]
        "Inundação, alagamento" # [cite: 31]
    ],

    "Ouvidorias e Informações Diversas": [
        "Informações 1746 - SMS", # [cite: 1]
        "Cemitérios e Serviços Funerários", # [cite: 3]
        "Evento", # [cite: 4]
        "Diversos - 1746", # [cite: 6]
        "Ouvidoria - CLF", # [cite: 6]
        "Ouvidoria - CMTC", # [cite: 6]
        "Ouvidoria Rio-Águas", # [cite: 8]
        "Enchentes e saneamento", # [cite: 8]
        "Ouvidoria SECONSERMA", # [cite: 8]
        "Informação solicitada - SECONSERVA", # [cite: 8]
        "Informação solicitada - SUBSC", # [cite: 8]
        "Ouvidoria SMDUE", # [cite: 9]
        "Diversos - SMF", # [cite: 9]
        "Ouvidoria - SMIH", # [cite: 10]
        "Ouvidoria  -  SMI", # [cite: 10]
        "Obras Públicas - SMI", # [cite: 10]
        "Ouvidoria SUBEM", # [cite: 10]
        "Fora do âmbito municipal - SMS", # [cite: 10]
        "Diversos - IplanRio", # [cite: 13]
        "Diversos - RIOLUZ", # [cite: 13]
        "Informação solicitada - RIOLUZ", # [cite: 13]
        "Ouvidoria SEMESQV", # [cite: 14]
        "Informação solicitada - SMDEIS", # [cite: 14]
        "Informação solicitada - SMS", # [cite: 14]
        "Informação solicitada - CLF", # [cite: 15]
        "Diversos - Casa Civil", # [cite: 15]
        "Diversos - CGC", # [cite: 15]
        "Ouvidoria - CCPAR", # [cite: 16]
        "Fora do âmbito municipal - Rioluz", # [cite: 16]
        "Informação solicitada - Rio Urbe", # [cite: 16]
        "Questões administrativas -  SMU", # [cite: 16]
        "Ouvidoria SUBPD", # [cite: 16]
        "Diversos - CLF", # [cite: 17]
        "Ouvidoria PGM", # [cite: 17]
        "Ouvidoria SPM-Rio", # [cite: 17]
        "Informação solicitada -  SMPU", # [cite: 17]
        "Ouvidoria - SMC", # [cite: 18]
        "Informação solicitada - CCU", # [cite: 18]
        "Diversos - SEGOVI", # [cite: 19]
        "Diversos - SMTE", # [cite: 19]
        "Ouvidoria - SMPU", # [cite: 19]
        "Informação solicitada - PGM", # [cite: 20]
        "Ouvidoria RIOLUZ", # [cite: 20]
        "Diversos - CGM", # [cite: 21]
        "Informação solicitada - RIO-AGUAS", # [cite: 21]
        "Programas da SEMESQV", # [cite: 22]
        "Ouvidoria SUBEL", # [cite: 22]
        "Ouvidoria - SMA", # [cite: 23]
        "Loteamentos", # [cite: 23]
        "Informação solicitada - SUBEL", # [cite: 23]
        "Fora do âmbito municipal - Seconserva", # [cite: 23, 24]
        "Informação solicitada - SMC", # [cite: 24]
        "Diversos - CCPAR", # [cite: 24]
        "Ouvidoria - Geral", # [cite: 24]
        "Informação solicitada - IPLANRIO", # [cite: 24]
        "Diversos - SECONSERVA", # [cite: 24]
        "Ouvidoria SMCT", # [cite: 24]
        "Diversos - PGM", # [cite: 24]
        "Diversos - RIO-ÁGUAS", # [cite: 24]
        "Mapas", # [cite: 24]
        "Informação solicitada - SUBPD", # [cite: 25]
        "Ouvidoria SMDEIS", # [cite: 26]
        "Informação solicitada - CCPAR", # [cite: 26]
        "Diversos - SUBPD", # [cite: 26]
        "CFS", # [cite: 26]
        "Administrativo  SUBEL", # [cite: 27]
        "Diversos - SMC", # [cite: 27]
        "Ouvidoria SMSDC/CAP1.0", # [cite: 28]
        "Informação solicitada - CGM", # [cite: 28]
        "Diversos - MULTIRIO", # [cite: 29]
        "Informação solicitada - 1746", # [cite: 29]
        "Recursos humanos - MULTIRIO", # [cite: 29]
        "Ouvidoria - IVISA", # [cite: 29]
        "Informação solicitada - MULTIRIO", # [cite: 29]
        "Ouvidoria SMSDC/CAP3.3", # [cite: 29]
        "Ouvidoria SMSDC/CAP2.1", # [cite: 29]
        "Vistorias na orla marítima e das lagoas", # [cite: 30]
        "Ouvidoria SMSDC/CAP3.1", # [cite: 30]
        "Ouvidoria SMSDC/CAP5.1", # [cite: 30]
        "Informação solicitada - Cidade das Artes", # [cite: 31]
        "Diversos", # [cite: 31]
        "Apoio" # [cite: 32]
    ]
}